import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const Navigation = [
    {
      name : "Home",
      href : "/"
    },
    {
      name : "Product",
      href : "/product"
    },
    {
      name : "Contact Us",
      href : "/contact"
    },
    {
      name : "About Us",
      href : "/about"
    }
  ]
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
        {Navigation.map((item)=>{
          return(
            <Link className="mr-9 " key={item.name} href={item.href}>{item.name}</Link>
          )
        })}
        </div>
        <div className="mt-5">
        {children}
        </div>
      </body>
    </html>
  );
}
